import { execSync } from 'child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

mkdirSync('build', { recursive: true })
mkdirSync('src/wasm', { recursive: true })

const isDebug = process.argv.includes('--debug')
const ascFlags = isDebug
  ? '--debug --runtime stub'
  : '--optimize --runtime stub --noAssert'

const asc = resolve('node_modules/.bin/asc')

execSync(`${asc} assembly/index.ts --outFile build/ai.wasm ${ascFlags}`, {
  stdio: 'inherit',
})

const wasm = readFileSync('build/ai.wasm')
const base64 = wasm.toString('base64')
const sizeBytes = wasm.length
const sizeKB = (sizeBytes / 1024).toFixed(1)

writeFileSync(
  'src/wasm/ai-wasm.ts',
  [
    '// Auto-generated by scripts/build-wasm.js — do not edit manually',
    '// Rebuild with: pnpm wasm:build',
    `// Source: assembly/index.ts -> build/ai.wasm (${sizeKB} KB, ${sizeBytes} bytes)`,
    '',
    `export const AI_WASM_BASE64 = '${base64}'`,
    '',
  ].join('\n'),
)

console.log(`WASM bundle generated: ${sizeBytes} bytes (${sizeKB} KB)`)