// Auto-generated by scripts/build-wasm-all.js — do not edit manually
// Rebuild with: pnpm wasm:build
// Source: assembly/index.ts → build/ai.wasm (0.2 KB, 198 bytes)

export const AI_WASM_BASE64 =
  'AGFzbQEAAAABDwJgBH9/f38Bf2ACf38BfwMDAgABBQMBAAAHOQMUemlwSGV1cmlzdGljRGlzdGFuY2UAABV6aXBEaXJlY3Rpb25Gcm9tRGVsdGEAAQZtZW1vcnkCAApmAiMAIAAgAmsgAiAAayAAIAJKGyABIANrIAMgAWsgASADShtqC0AAIAFFIABBf0ZxBEBBAA8LIAFFIABBAUZxBEBBAQ8LIABFIAFBf0ZxBEBBAg8LIABFIAFBAUZxBEBBAw8LQX8L'

// Size: 0.2 KB (198 bytes)
// Encoded: 2026-04-17T10:51:40.728Z
