// Sources: https://patents.google.com/patent/US5966526A/en and
// https://github.com/loociano/tamagotchi-tech-specs/blob/master/index.md
//
// Build path:
// apps/tamagotchi-engine/assembly/index.ts -> build/pet.wasm -> src/wasm/pet-wasm.ts

import { execSync } from 'child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'

const isDebug = globalThis.process.argv.includes('--debug')

mkdirSync('build', { recursive: true })
mkdirSync('src/wasm', { recursive: true })

const ascFlags = isDebug ? '--debug --runtime stub' : '--optimize --runtime stub --noAssert'

execSync(`pnpm -C ../.. exec asc assembly/index.ts --outFile build/pet.wasm ${ascFlags}`, {
  stdio: 'inherit',
})

const wasm = readFileSync('build/pet.wasm')
const base64 = wasm.toString('base64')
const sizeBytes = wasm.length
const sizeKB = (sizeBytes / 1024).toFixed(1)

writeFileSync(
  'src/wasm/pet-wasm.ts',
  [
    '// Auto-generated by scripts/build-wasm.js — do not edit manually',
    '// Rebuild with: pnpm wasm:build',
    `// Source: assembly/index.ts -> build/pet.wasm (${sizeKB} KB, ${sizeBytes} bytes)`,
    '',
    `export const PET_WASM_BASE64 = '${base64}';`,
    '',
  ].join('\n'),
)

globalThis.console.log(
  `✓ Tamagotchi WASM helper: ${sizeBytes} bytes (${sizeKB} KB) -> src/wasm/pet-wasm.ts`,
)