// Auto-generated by scripts/build-wasm.js — do not edit manually
// Rebuild with: pnpm wasm:build
// Source: assembly/index.ts → build/ai.wasm (0.0 KB, 25 bytes)

export const AI_WASM_BASE64 = 'AGFzbQEAAAAFAwEAAAcKAQZtZW1vcnkCAA=='
